# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 09:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='future_rcp45',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('index_su', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_fd', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_id', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tr', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_gsl', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_dtr', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_txx', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tnx', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_txn', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tnn', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rx1day', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rx5day', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_sdii', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r10mm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r20mm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rnnmm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_cdd', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_cwd', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_future_rpc45',
            },
        ),
        migrations.CreateModel(
            name='future_rcp85',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('index_su', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_fd', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_id', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tr', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_gsl', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_dtr', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_txx', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tnx', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_txn', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tnn', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rx1day', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rx5day', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_sdii', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r10mm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r20mm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rnnmm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_cdd', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_cwd', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_future_rpc85',
            },
        ),
        migrations.CreateModel(
            name='grid',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('point', django.contrib.postgres.fields.jsonb.JSONField()),
                ('coordinates', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_grid',
            },
        ),
        migrations.CreateModel(
            name='hist_rpc45',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('index_wsdi', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_csdi', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tn10p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tx10p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tn90p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tx90p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r95ptot', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r99ptot', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_prctot', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_hist_rpc45',
            },
        ),
        migrations.CreateModel(
            name='hist_rpc85',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('index_wsdi', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_csdi', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tn10p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tx10p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tn90p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tx90p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r95ptot', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r99ptot', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_prctot', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_hist_rpc85',
            },
        ),
        migrations.CreateModel(
            name='historical',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('index_su', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_fd', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_id', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tr', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_gsl', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_dtr', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_txx', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tnx', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_txn', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_tnn', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rx1day', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rx5day', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_sdii', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r10mm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_r20mm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_rnnmm', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_cdd', django.contrib.postgres.fields.jsonb.JSONField()),
                ('index_cwd', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_historical',
            },
        ),
        migrations.CreateModel(
            name='measure_prec',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('ms_avg', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ms_max', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ms_min', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_measure_prec',
            },
        ),
        migrations.CreateModel(
            name='measure_temp',
            fields=[
                ('id', models.IntegerField(db_column='grid_id', primary_key=True, serialize=False)),
                ('ms_avg', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ms_max', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ms_min', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'climate_measure_temp',
            },
        ),
        migrations.DeleteModel(
            name='feature',
        ),
        migrations.DeleteModel(
            name='Ts',
        ),
    ]
