# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0003_auto_20170328_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='future_rcp85',
            old_name='fd',
            new_name='index_fd',
        ),
        migrations.RenameField(
            model_name='future_rcp85',
            old_name='su',
            new_name='index_su',
        ),
    ]
