# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 15:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_avg_rcp85_his_rcp85'),
    ]

    operations = [
        migrations.CreateModel(
            name='cal_maxmin',
            fields=[
                ('id', models.IntegerField(db_column='cal_id', primary_key=True, serialize=False)),
                ('pr_avg', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pr_max', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pr_min', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ts_avg', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ts_max', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ts_min', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'cal_rcp85',
            },
        ),
    ]
